name: Build and Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build -- --sourcemap

      - name: Compress the app
        run: zip -r dist.zip dist/

      - name: Generate suffix
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        id: datetime
        run: echo "suffix=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create Prerelease
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v3
        with:
          tag_name: prerelease-${{ steps.datetime.outputs.suffix }}
          prerelease: true
          files: dist.zip

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v3
        with:
          files: dist.zip
